spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: rag-1
  ai:
    vertex:
      ai:
        gemini:
          project-id: boreal-forest-471802-g5
          location: us-central1
          chat:
            options:
              model: gemini-2.0-flash
              temperature: 0.2
        embedding:
          project-id: boreal-forest-471802-g5
          location: us-central1
          model: text-embedding-004
          enabled: true
          text:
            options:
              dimensions: 768
    huggingface:
      embedding:
        enabled: false
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: embedded
    vectorstore:
      elasticsearch:
        index-name: my_rag_data
        initialize-schema: true
        dimensions: 768
        similarity: cosine

  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: RFxjWU6af+A9b*yQ4Wur



logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG
